app/models.py
"""

Contains models for Flask application

"""

""" Surveys DB model """

class Surveys(db.model):
	""" Surveys """
	
	survey_name = db.column(db.String(32), nullable=False, primary_key=True)
	survey_description = db.column(db.String(256))

app/__init__.py
"""

Flask init file

"""

from flask import Flask
from app.views import home

def create_app():
    app = Flask(__name__)
     
    # Register the blueprint
    app.register_blueprint(home)
    
    return app

app/views.py
"""

Contains routes for Flask application

"""

from flask import Blueprint, redirect, render_template, url_for

home = Blueprint('home', __name__)

@home.route('/')
def index():
    return render_template('home.html')

app/templates/base.html
<!DOCTYPE html>
<html lng="en">
<head>
	{% block head %}
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
	
	<title>Gamevey {% block title %}{% endblock %}</title>
	{% endblock %}
</head>
<body>
	<nav class="navbar-expand-lg navbar-dark bg-dark">
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		
		<div class="collapse navbar-collapse" id="navbar-content">
			<ul class="navbar-nav mr-auto>
				<li class="nav-item>
					<a class="nav-link" href={{ url_for('home.index') }}>Home</a>
				</li>
			</ul>
		</div>
	</nav>
	
	<div class="container">
		{% block content %}
		{% endblock %}
	</div>
</body>
</html>

app/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
	<h1>Welcome to Gamevey</h1>
{% endblock %}